name: Publish Docs

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out docs
      uses: actions/checkout@v4
      with:
        path: src/DuckDB.NET-Docs
    
    - name: Check out DuckDB.NET
      uses: actions/checkout@v4
      with:
        repository: Giorgi/DuckDB.NET
        ref: nightly-scalar-function
        path: src/DuckDB.NET
        fetch-depth: 0
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: src/DuckDB.NET/global.json
        
    - name: Build
      run: dotnet build src/DuckDB.NET/DuckDB.NET.sln --configuration Release
    
    - uses: nunit/docfx-action@v3.4.1
      name: Build Documentation
      with:
        args: src/DuckDB.NET-Docs/docfx.json
        
    - name: Deploy to Netlify
      uses: South-Paw/action-netlify-cli@v2
      id: netlify
      with:
        # note that the --json flag has been passed so we can parse outputs
        args: deploy --prod --json --dir './src/DuckDB.NET-Docs/_site' --message 'Auto deploy [${{ github.sha }}]'
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    
