name: Publish Docs

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out docs
      uses: actions/checkout@v4
      with:
        path: src/DuckDB.NET-Docs
    
    - name: Check out DuckDB.NET
      uses: actions/checkout@v4
      with:
        repository: Giorgi/DuckDB.NET
        path: src/DuckDB.NET

    - uses: nunit/docfx-action@v2.4.0
      name: Build Documentation
      with:
        args: src/DuckDB.NET-Docs/docfx.json
        
    - name: Display structure of files
      run: ls -R     
    
