name: Publish Docs

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out docs
      uses: actions/checkout@v4
    
    - name: Check out DuckDB.NET
      uses: actions/checkout@v4
      with:
        repository: Giorgi/DuckDB.NET

    - name: Display structure of files
      run: ls -R     
    
